In [1]:
import numpy as np

a = np.array([10, 20, 30, 40, 50, 60])

print(a[1:4])

[20 30 40]


In [ ]:
print(a[:3])      
print(a[2:])      
print(a[::2])     
print(a[::-1])    

[10 20 30]
[30 40 50 60]
[10 30 50]
[60 50 40 30 20 10]


In [7]:
a = np.arange(1, 13)

print(a)
print("\n")
print(a.reshape(2, 6))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [8]:
arr = np.array([1, 2, 3, 4])

result = arr + 10

print(result)

[11 12 13 14]
